# Project Configuration for LLMOps Course

# Development environment
dev:
  #catalog: llmops_dev # Databricks Free Edition
  catalog: mlops_dev
  #schema: arxiv # Databricks Free Edition
  schema: joaontor
  volume: arxiv_files
  llm_endpoint: databricks-llama-4-maverick
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: 7077f4cb0e616c62
  vector_search_endpoint: llmops_course_vs_endpoint
  #genie_space_id: 01f13752501d170c8bd8b67cc2e6b5b9 # Databricks Free Edition
  genie_space_id: 01f13c0baa971196b99d2cd3e2e91214
  usage_policy_id: 7dde2fae-0d6a-4c7c-aa36-85d95ffbdce0

# Acceptance/Staging environment
acc:
  catalog: llmops_dev
  schema: arxiv
  volume: arxiv_files
  llm_endpoint: databricks-meta-llama-3-1-70b-instruct
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: 7077f4cb0e616c62
  vector_search_endpoint: llmops_course_vs_endpoint
  # genie_space_id: 01f13752501d170c8bd8b67cc2e6b5b9 # Databricks Free Edition
  genie_space_id: 01f13c0baa971196b99d2cd3e2e91214
  usage_policy_id: 7dde2fae-0d6a-4c7c-aa36-85d95ffbdce0

# Production environment
prd:
  catalog: llmops_dev
  schema: arxiv
  volume: arxiv_files
  llm_endpoint: databricks-meta-llama-3-1-70b-instruct
  embedding_endpoint: databricks-gte-large-en
  warehouse_id: 7077f4cb0e616c62
  vector_search_endpoint: llmops_course_vs_endpoint
  # genie_space_id: 01f13752501d170c8bd8b67cc2e6b5b9 # Databricks Free Edition
  genie_space_id: 01f13c0baa971196b99d2cd3e2e91214
  usage_policy_id: 7dde2fae-0d6a-4c7c-aa36-85d95ffbdce0

# Model configuration
model_config:
  temperature: 0.7
  max_tokens: 2000
  top_p: 0.95

# Vector search configuration
vector_search:
  embedding_dimension: 1024
  similarity_metric: cosine
  num_results: 5

# Chunking configuration
chunking:
  chunk_size: 512
  chunk_overlap: 50
  separator: "\n\n"
